movies/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    # 导航栏分类内容
    url(r'^home/pagenum=(\d*)/', views.home, name='home'),
    url(r'^movies/pagenum=(\d*)/', views.movies, name='movies'),
    url(r'^tvplay/pagenum=(\d*)/', views.tvplay, name='tvplay'),
    url(r'^variety/pagenum=(\d*)/', views.variety, name='variety'),
    url(r'^comic/pagenum=(\d*)/', views.comic, name='comic'),
    url(r'^search_details/keyword=(\w*)pagenum=(\d*)/',views.search_details,name='search_details'),
    # 电影详情
    url(r'^movie_details/mvid=(\d*)/', views.movie_details, name='movie_details'),
    # 用户相关
    url(r'^signup/', views.signup,name='signup'),
    url(r'^login/', views.login,name='login'),
    url(r'^logout/', views.logout,name='logout'),
    url(r'^checkUser/',views.checkUser),  # 检查用户名唯一性的
    url(r'^checkPassword/', views.checkPassword),  # 检查用户名唯一性的
    url(r'^userInfo/', views.userInfo, name='userInfo'),
    url(r'^update_password/', views.update_password, name='update_password'),
    # 购物
    url(r'^buy/',views.buy,name='buy'),
    url(r'^QRcode/',views.QRcode,name='QRcode'),
    url(r'^userCard/', views.userCard, name='userCard'),
    url(r'^deleteCart/cartid=(\d*)/', views.deleteCart, name='deleteCart'),


]

movies/movies/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/',include('app.urls',namespace='movies')),
]

movies/templates/common/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <title>{{ title }}</title>
    {#  导入css  和 js  #}
    <script src="https://npmcdn.com/jquery@3.1.0/dist/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css" rel="stylesheet">
    {#  子模型中扩展自己的css  #}
    {% block css %}

    {% endblock %}
    {# 子模型中扩展自己的js  #}
    {% block js %}

    {% endblock %}

</head>
<body>
{#    头 #}
{% block header %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'movies:home' 1 %}">小飞驴电影网</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li style="width: 100px;" class="active"><a href="{% url 'movies:home' 1 %}">首页<span class="sr-only">(current)</span></a></li>
                    <li style="width: 100px;"><a href="{% url 'movies:movies' 1 %}">电影</a></li>
                    <li style="width: 100px;"><a href="{% url 'movies:tvplay' 1 %}">电视剧</a></li>
                    <li style="width: 100px;"><a href="{% url 'movies:variety' 1 %}">综艺</a></li>
                    <li style="width: 100px;"><a href="{% url 'movies:comic' 1 %}">动漫</a></li>
                </ul>
                <form class="navbar-form navbar-left" method="post" action="{% url 'movies:search_details' '' 1 %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="search" placeholder="请输入要搜索的内容">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user1 %}
                    <li>
                        <a href="{% url 'movies:userInfo' %}" style="height: 50px;margin: 0;padding: 0;">
                            <img src="/static/upload/{{ user1.icon }}" alt="" style="width: 50px;border-radius: 25px;">尊敬的用户:{{ user1.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'movies:userInfo' %}">个人信息</a></li>
                            <li><a href="{% url 'movies:userCard' %}">我的购物车</a></li>
{#                            <li><a href="#">我的收藏</a></li>#}
                            <li><a href="{% url 'movies:update_password' %}">修改密码</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'movies:logout' %}">注销</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{% url 'movies:login' %}">登录</a></li>
                    <li><a href="{% url 'movies:signup' %}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}
{#    内容  #}
{% block content %}

{% endblock %}
{#  脚 #}
{% block footer %}
    <footer style="padding: 100px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>&copy; 2018 小飞驴, Inc. &middot;
                        <a href="#">Privacy</a> &middot;
                        <a href="#">Terms</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <div style="position: fixed; right: 5%; bottom: 10%;">
        <a class="back-to-top" href="#top">
            <img src="{% static 'img/top1.gif' %}"/>
        </a>
    </div>
{% endblock %}

{#导入js#}
<script src="https://npmcdn.com/jquery@3.1.0/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.min.js"></script>
</body>
</html>