movies/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    # 导航栏分类内容
    url(r'^home/pagenum=(\d*)/', views.home, name='home'),
    url(r'^movies/pagenum=(\d*)/', views.movies, name='movies'),
    url(r'^tvplay/pagenum=(\d*)/', views.tvplay, name='tvplay'),
    url(r'^variety/pagenum=(\d*)/', views.variety, name='variety'),
    url(r'^comic/pagenum=(\d*)/', views.comic, name='comic'),
    url(r'^search_details/keyword=(\w*)pagenum=(\d*)/',views.search_details,name='search_details'),
    # 电影详情
    url(r'^movie_details/mvid=(\d*)/', views.movie_details, name='movie_details'),
    # 用户相关
    url(r'^signup/', views.signup,name='signup'),
    url(r'^login/', views.login,name='login'),
    url(r'^logout/', views.logout,name='logout'),
    url(r'^checkUser/',views.checkUser),  # 检查用户名唯一性的
    url(r'^checkPassword/', views.checkPassword),  # 检查用户名唯一性的
    url(r'^userInfo/', views.userInfo, name='userInfo'),
    url(r'^update_password/', views.update_password, name='update_password'),
    # 购物
    url(r'^buy/',views.buy,name='buy'),
    url(r'^QRcode/',views.QRcode,name='QRcode'),
    url(r'^userCard/', views.userCard, name='userCard'),
    url(r'^deleteCart/cartid=(\d*)/', views.deleteCart, name='deleteCart'),


]

movies/movies/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/',include('app.urls',namespace='movies')),
]

movies/templates/user/login.html
{% extends 'common/base.html' %}
{% load  static %}
{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
		<div class="body">
			<div class="container container-login">
				<div class="signup-forms">
					<div class="login-box" style="display: block;">
						<form action="{% url 'movies:login' %}" method="post">
                            {% csrf_token %}
							<div class="form-group">
								<label for="exampleInputEmail1">用户名</label>
								<input id="username" name="username" type="text" class="form-control" placeholder="请输入用户名" required>
							</div>
							<div class="form-group">
								<label for="exampleInputPassword1">密码</label>
								<input id="password" name="password" type="password" class="form-control" placeholder="请输入密码" required>
							</div>
							<div class="checkbox">
								<label><input type="checkbox">记住密码</label>
							</div>
							<button type="submit" class="btn btn-default">登录</button>
						</form>
						<div class="" style="width: 200px;position: absolute;top: 50px;right: 10px;">
							<a href="{% url 'movies:home' 1 %}"><img src="{% static 'img/logo.jpg' %}" style="width: 150px;" /></a>
						</div>
						<div class="bottom-link">
							还没有帐号?
							<a href="{% url 'movies:signup' %}">马上注册</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--<div class="">
			<img src="img/background.jpg" style="width: auto; height: 632px; margin-top: -7.5px;"/>
		</div>-->
		<div class="fullscreen-bg" style="background-image: url('{{ rdimg }}');background-size: 100%;">
        <img src="{{ rdimg }}"
             style="width: 100%; height: 100%; margin-top: -7.5px;">
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

movies/templates/user/signup.html
{% extends 'common/base.html' %}
{% load  static %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/userVerify.js' %}"></script>
{% endblock %}
{% block header %}
{% endblock %}

{% block content %}
    <div class="body">
        <div class="container container-login">
            <div class="signup-forms">
                <div class="signup-box" style="display: block;">
                    <form action="{% url 'movies:signup' %}" method="post" id="f1" onsubmit="return formsubmit()">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleInputEmail1">用户名</label><span id="s1" style="margin-left: 40px;"></span>
                            <input id="username" name="username" type="text" class="form-control"
                                   placeholder="请输入用户名" required>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">密码</label><span id="s2" style="margin-left: 40px;"></span>
                            <input id="password" name="pwd" type="password" class="form-control" placeholder="请输入密码" required>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">确认密码</label><span id="s3" style="margin-left: 40px;"></span>
                            <input id="cpassword" name="password" type="password" class="form-control"
                                   placeholder="请确认密码" required>
                        </div>
                        <button type="submit" class="btn btn-default">注册</button>
                    </form>
                    <div class="" style="width: 200px;position: absolute;top: 70px;right: 10px;">
                        <a href="{% url 'movies:home' 1 %}"><img src="{% static 'img/logo.jpg' %}" style="width: 150px;"/></a>
                    </div>
                    <div class="bottom-link">
                        已经注册?
                        <a href="{% url 'movies:login' %}">马上登录</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="fullscreen-bg" style="background-image: url('{{ rdimg }}');background-size: 100%;">
        <img src="{{ rdimg }}"
             style="width: 100%; height: 100%; margin-top: -7.5px;">
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

movies/templates/user/update_password.html
{% extends 'common/base.html' %}
{% load static %}
{% block css %}
    <style>
        #oldpwd,#password,#cpassword{
            width: 300px;
        }
    </style>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/update_password.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="page-header"><h2>修改密码</h2></div>
        <div class="row">
            <form action="{% url 'movies:update_password' %}" method="post" id="f1" onsubmit="return formsubmit()">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">旧密码</label><span id="s1" style="margin-left: 40px;"></span>
                    <input id="oldpwd" name="oldpwd" type="password" class="form-control" placeholder="请输入旧密码">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">新密码</label><span id="s2" style="margin-left: 40px;"></span>
                    <input id="password" name="newpwd" type="password" class="form-control" placeholder="请输入新密码" required>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label><span id="s3" style="margin-left: 40px;"></span>
                    <input id="cpassword" name="password" type="password" class="form-control"
                           placeholder="请确认密码" required>
                </div>
                <button type="submit" class="btn btn-default">确认</button>
            </form>
        </div>
    </div>
{% endblock %}

movies/templates/user/userCart.html
{% extends 'common/base.html' %}
{% load static %}
{% block css %}
    <style>
        .mv_ticket {
            margin: 0 auto;
            position: fixed;
            padding: 0;
            width: 300px;
            height: 400px;
            left: 500px;
            top: 100px;
            z-index: 5;
            background: #ffffff;
            background-size: auto;
            border-radius: 10px;
            display: none;
        }
    </style>
{% endblock %}
{% block js %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="page-header"><h2>电影票</h2></div>
        <table class="table table-bordered table-hover definewidth m10">
            <thead>
            <tr>
                <th>电影id</th>
                <th>电影标题</th>
                <th>票数</th>
                <th>总价</th>
                <th>操作</th>
            </tr>
            </thead>
            {% for row in shopMovies %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.movieid.name }}</td>
                    <td>{{ row.quantity }}</td>
                    <td>{{ row.price }}</td>
                    <td>
                        <a id='look_ticket{{ row.id }}'>查看电影票</a> |
                        <a href="{% url 'movies:deleteCart' row.id %}">删除记录</a>
                    </td>
                    <div class="mv_ticket" id="t{{ row.id }}" style="background: url({{ row.movieid.img }}) repeat-x;">
                        <span class="glyphicon glyphicon-remove" id="cancel{{ row.id }}"
                              style=" position: absolute;right: 10px;top: 10px;font-size: 25px;"></span>
                        <div style="height: 30px;width: 200px;margin: 50px;"><span id="choose_seats"
                                                                                   style="color: white;font-size: 20px;border: 1px solid red;">{{ row.movieid.name }}</span>
                        </div>
                        <br>
                        <div style="height: 30px;width: 200px;margin-left: 50px;margin-top: 20px;"><span
                                id="choose_seats" style="color: white;font-size: 20px;border: 1px solid red;">{{ row.seats }}</span></div>
                        <br>
                        <div style="height: 30px;width: 200px;margin-left: 50px;margin-top: 20px;"><span
                                style="color: white;font-size: 20px;border: 1px solid red;">总价为:￥<span
                                id="price">{{ row.price }}</span></span></div>
                    </div>
                    <script type="text/javascript">
                        $(function () {
                            $('#look_ticket{{ row.id }}').click(function () {
                                $('#t{{ row.id }}').css('display', 'block');
                            });
                            $('#cancel{{ row.id }}').click(function () {
                                $('#t{{ row.id }}').css('display', 'none');
                            })
                        })
                    </script>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

movies/templates/user/userInfo.html
{% extends 'common/base.html' %}
{% load static %}

{% block css %}
    <style>
        .container p{
            font-size: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="page-header"><h2>个人信息</h2></div>
        <img src="/static/upload/{{ user1.icon }}" alt="" style="width: 100px;height:100px;border-radius: 50px;">
        <p>用户名: {{ user1.username }}</p>
        {% if user1.email %}
            <p>邮箱: {{ user1.email }}</p>
        {% else %}
            <p>邮箱: </p>
        {% endif %}

        {% ifequal user1.sex 1 %}
            <p>性别: 男</p>
        {% else %}
            <p>性别: 女</p>
        {% endifequal %}
        <p>年龄: {{ user1.age }}</p>

    </div>
{% endblock %}